<?php

//ESTE ARCHIVO ES PARA ESTABLECER CONEXION CON LA BD Y EVITAR REPETIR EL CODIGO EN TODOS LOS ARCHIVOS

function conectar(){ //FUNCION QUE EJECUTAREMOS CUANDO IMPORTEMOS ESTE ARCHIVO

    $host = "localhost"; //LA DIRECCION DEL HOST DE LA BD
    $user ="root"; //EL USUARIO CON EL QUE ACCEDEREMOS A LA BD
    $pass =""; //LA CONTRASEÑA DEL USUARIO QUE LE PROPORCIONAMOS
    $bd ="datosamigos"; //LA BD A LA QUE SE CONECTARA
    $con=mysqli_connect($host,$user,$pass); //SE CREA LA CONECCION CON EL HOST Y SE INICIA SESION
    mysqli_select_db($con,$bd); //INGRESAMOS A LA BD QUE USAREMOS
    return $con; //SE REGRESA ESTA VARIABLE, YA QUE CON ESTA SE PODRAN EJECUTAR SENTENCIAS SQL


}

?>